#!/bin/bash -e

#enable deice tree overlay
echo "dtoverlay=dwc2" | sudo tee -a /boot/config.txt
echo "dwc2" | sudo tee -a /etc/modules

#enable libcomposite driver
sudo echo "libcomposite" | sudo tee -a /etc/modules

# TBD ....
